## Question 1

Importing libraries

In [1]:
import numpy as np
from PIL import Image

Function to convolve Image and Kernel

In [2]:
def convolve_image_kernel(image, kernel) : 
    
    #Finding the shape of the image
    image_x_shape, image_y_shape = image.shape[0], image.shape[1]
    
    #Finding the shape of the kernel
    kernel_x_shape, kernel_y_shape = kernel.shape[0], kernel.shape[1]
    
    #Defining the output convolved image shape
    convolution_image = np.zeros((int((image_x_shape - kernel_x_shape) + 1), int((image_y_shape - kernel_y_shape) + 1)))
    
    #Convolution process
    for j in range(image_y_shape) : 
        
        if j > image_y_shape - kernel_y_shape : 
            break
        
        for i in range(image_x_shape) : 
            
            if i > image_x_shape - kernel_x_shape : 
                break
            
            convolution_image[i, j] = (kernel * image[i: i + kernel_x_shape, j: j + kernel_y_shape]).sum()      
            
    return convolution_image

Testing funtion

In [3]:
image = np.array([[12, 12, 12, 12, 12, 12], [10, 10, 10, 10, 10, 10], [8, 8, 8, 8, 8, 8], 
                  [6, 6, 6, 6, 6, 6], [4, 4, 4, 4, 4, 4], [2, 2, 2, 2, 2, 2]])
kernel = np.array([[3, 3, 3], [3, 3, 3], [3, 3, 3]])
convolution_image = convolve_image_kernel(image, kernel)

print(f'Image is :\n {image}')
print(f'Kernel is :\n {kernel}')
print(f'Convolved Image is :\n {convolution_image}')

Image is :
 [[12 12 12 12 12 12]
 [10 10 10 10 10 10]
 [ 8  8  8  8  8  8]
 [ 6  6  6  6  6  6]
 [ 4  4  4  4  4  4]
 [ 2  2  2  2  2  2]]
Kernel is :
 [[3 3 3]
 [3 3 3]
 [3 3 3]]
Convolved Image is :
 [[270. 270. 270. 270.]
 [216. 216. 216. 216.]
 [162. 162. 162. 162.]
 [108. 108. 108. 108.]]


Loading test image

In [4]:
im = Image.open('Test_Image.png')
rgb = np.array(im.convert('RGB'))
r = rgb [:, :, 0]
Image.fromarray(np.uint8(r)).show( )

Testing the Image for Kernel 1

In [5]:
kernel_1 = np.array([[-1, -1, -1],[-1, 8, -1],[-1, -1, -1]])
convolution_image_1 = convolve_image_kernel(r, kernel_1)
Image.fromarray(np.uint(convolution_image_1)).show()

Testing the Image for Kernel 2

In [6]:
kernel_2 = np.array([[0, -1, 0],[-1, 8, -1],[0, -1, 0]])
convolution_image_2 = convolve_image_kernel(r, kernel_2)
Image.fromarray(np.uint(convolution_image_2)).show()